export {default as Navbar}  from './Navbar'
export {default as Footer} from './Footer'
export {default as Banner} from './Banner'
export  {default as About} from './About'
export {default as Skills} from './Skills'